---
name: "sast"

on:
    pull_request: {}
    push:
        branches:
            - "main"

jobs:
    run:
        runs-on: "ubuntu-20.04"

        steps:
            - uses: "actions/checkout@v2"
            - uses: "pnpm/action-setup@v2.0.1"
              with:
                  version: "latest"
            - uses: "actions/setup-node@v2"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - run: "make install"
            - uses: "snyk/actions/node@master"
              continue-on-error: true
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: "monitor"
