---
name: "sast"

on:
    pull_request: {}
    push:
        branches:
            - "main"
    schedule:
        - cron: "19 19 * * 4"

jobs:
    snyk:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@v3"
            - uses: "pnpm/action-setup@v2.0.1"
              with:
                  version: "latest"
            - uses: "actions/setup-node@v2"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - run: "make install"
            - uses: "snyk/actions/node@master"
              continue-on-error: true
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: "monitor"

    codeql:
        runs-on: "ubuntu-latest"

        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                language: ["java", "javascript"]

        steps:
            - uses: "actions/checkout@v3"
            - uses: "github/codeql-action/init@v2"
              with:
                  languages: ${{ matrix.language }}
            - uses: "pnpm/action-setup@v2.0.1"
              with:
                  version: "latest"
            - uses: "actions/setup-node@v2"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "actions/setup-java@v2"
              with:
                  java-version: "17"
                  distribution: "temurin"
                  cache: "gradle"
            - run: "make install"
            - run: "make compile"
            - uses: "github/codeql-action/analyze@v2"
